Repository codesandbox/codesandbox-client, pull requests merged in 2019-12, with the labels that each got.

#3074 🔨 Switch Appearance to use useOvermind
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx
  packages/common/src/components/Preference/PreferenceText/elements.ts
  packages/common/src/components/Preference/PreferenceText/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3071 🔨 Switch SelectSandboxModal to use useOvermind
  packages/app/src/app/overmind/namespaces/profile/actions.ts
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/elements.js
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/elements.ts
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/index.js
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/index.tsx
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/elements.ts
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/index.tsx
  packages/common/src/utils/get-sandbox-name.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3070 🔨 Switch TemplateItem to use useOvermind
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem.tsx
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3122 Fix pipeline
  packages/app/src/app/overmind/effects/vscode/initializers.ts
  packages/common/src/__snapshots__/theme.test.ts.snap
  packages/common/src/themes/codesandbox-black.js
  packages/common/src/themes/codesandbox-black.json
Labels: 🏗️ CI/CD, 🔥 Critical, 🚨 ASAP

#3109 Fix parsedConfigurations type
  packages/app/config/babel.dev.js
  packages/app/config/babel.prod.js
  packages/app/package.json
  packages/app/src/app/overmind/namespaces/editor/internalActions.ts
  packages/app/src/app/overmind/namespaces/editor/state.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Server/Tasks.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Server/index.tsx
  packages/common/src/templates/configuration/types.ts
  packages/common/src/templates/template.ts
  yarn.lock
Labels: 📝 Types

#3127 🔨 Switch TemplateItem to use useOvermind
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem.tsx
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/index.tsx
Labels: 🔧 Fix, 🔨 Refactor, 🧠 Overmind

#3118 🔨 Switch VSCodePlaceholder to use useOvermind
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/KeyMapping/elements.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/KeyMapping/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/KeyMapping/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/OpenVSCodeSettingsButton/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/OpenVSCodeSettingsButton/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3131 Add checks for patron redirect + remove badge from editor
  packages/app/src/app/pages/Patron/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Header.tsx
Labels: enhancement

#3125 [fix] add missing (,) in ci.json
  packages/homepage/content/docs/8-ci.md
Labels: 📚 Documentation

#3144 🔨 Switch LikeHeart to use useOvermind
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/LikeButton/LikeButton.tsx
  packages/app/src/app/pages/common/LikeHeart/MaybeTooltip.tsx
  packages/app/src/app/pages/common/LikeHeart/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3120 🔨 Switch AliasDeploymentButton to use useOvermind
  packages/app/src/app/overmind/namespaces/deployment/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/AliasDeploymentButton/AliasDeploymentButton.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3142 🔨 Switch DashboardChangelog to use useOvermind
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/Helmet.tsx
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/elements.ts
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/index.tsx
  packages/common/src/components/Button/elements.tsx
  packages/common/src/components/Button/index.tsx
  packages/common/src/components/Modal/Modal.tsx
  packages/common/src/components/MultiAction/elements.ts
  packages/common/src/components/ProgressButton/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3068 🔨 Switch NetlifyLogs to use useOvermind
  packages/app/src/app/pages/common/Modals/NetlifyLogs/elements.ts
  packages/app/src/app/pages/common/Modals/NetlifyLogs/index.tsx
  packages/app/src/app/pages/common/Modals/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3062 🔨 Switch SignOutNoticeModal to use useOvermind
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/elements.ts
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3058 🔨 Switch CLIInstructions to use useOvermind
  packages/app/src/app/pages/CliInstructions/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3121 🔨 Switch CLI to use useOvermind
  packages/app/src/app/pages/CLI/Prompt/elements.ts
  packages/app/src/app/pages/CLI/Prompt/index.tsx
  packages/app/src/app/pages/CLI/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3061 🔨 Switch Curator to use useOvermind
  packages/app/src/app/components/DelayedAnimation.ts
  packages/app/src/app/overmind/namespaces/explore/actions.ts
  packages/app/src/app/pages/Curator/elements.ts
  packages/app/src/app/pages/Curator/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/PickButton/PickButton.tsx
  packages/app/src/app/pages/index.tsx
  packages/common/src/types/index.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3147 Delete DashboardChangelog & SignOutNoticeModal
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/elements.ts
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/index.tsx
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/Helmet.tsx
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/elements.ts
  packages/app/src/app/pages/common/Modals/Changelog/Dashboard/index.tsx
Labels: 🔨 Refactor

#3101 Extract MostUsedSandbox from CreateNewSandbox
  packages/app/src/app/components/CreateNewSandbox/MostUsedSandbox/elements.ts
  packages/app/src/app/components/CreateNewSandbox/MostUsedSandbox/index.tsx
  packages/app/src/app/components/CreateNewSandbox/elements.ts
  packages/app/src/app/components/CreateNewSandbox/index.tsx
Labels: 🔨 Refactor

#3054 🔨 Switch GitHub to use useOvermind
  packages/app/src/app/pages/GitHub/elements.ts
  packages/app/src/app/pages/GitHub/index.tsx
  packages/app/src/app/pages/GitHub/main.js
Labels: 🔨 Refactor, 🧠 Overmind

#3055 🔨 Switch ChangeSubscription to use useOvermind
  packages/app/src/app/overmind/namespaces/patron/actions.ts
  packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/elements.ts
  packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.tsx
  packages/app/src/app/pages/Patron/PricingModal/PricingChoice/index.tsx
  packages/common/src/types/index.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3057 🔨 Switch NewSandbox to use useOvermind
  packages/app/src/app/pages/NewSandbox/elements.ts
  packages/app/src/app/pages/NewSandbox/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2887 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.js to use Overmind #2885
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#3148 fix(workspace): fix overflow on WorkspaceItem's children
  packages/app/src/app/pages/Sandbox/Editor/Workspace/OpenedTabs/SaveIcon.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/OpenedTabs/elements.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/OpenedTabs/index.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/WorkspaceItem/index.tsx
Labels: UI/UX, blocked

#2880 refactored /app/src/app/pages/Dashboard/Sidebar/index.tsx dashboard sandbox index to overmind
  packages/app/src/app/pages/Dashboard/Sidebar/index.js
  packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#3153 Delete ZenModeIntroductionModal, since it's not used anymore
  packages/app/src/app/pages/Sandbox/ZenModeIntroductionModal/elements.ts
  packages/app/src/app/pages/Sandbox/ZenModeIntroductionModal/index.tsx
Labels: 🔨 Refactor

#3063 🔨 Switch Live to use useOvermind
  packages/app/src/app/overmind/namespaces/live/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/index.tsx
Labels: blocked, 🔨 Refactor, 🧠 Overmind

#2769 🔨 Refactor, 🧠 Overmind, refactored OpenedTabs to use Overmind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/OpenedTabs/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/WorkspaceItem/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/elements.ts
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2885 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.js to use Overmind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2922 🔨 Refactor, 🧠 Overmind | /app/pages/common/Modals/DeploymentModal/index.js
  .all-contributorsrc
  README.md
  packages/app/src/app/components/IntegrationModal/IntegrationModal.tsx
  packages/app/src/app/pages/common/Modals/DeploymentModal/Cube/elements.js
  packages/app/src/app/pages/common/Modals/DeploymentModal/Cube/index.js
  packages/app/src/app/pages/common/Modals/DeploymentModal/DeploymentModal.tsx
  packages/app/src/app/pages/common/Modals/DeploymentModal/elements.ts
  packages/app/src/app/pages/common/Modals/DeploymentModal/index.ts
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2881 refactored content editor tabs packages/app/src/app/pages/Sandbox/Editor/Content/Tabs/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Content/Tabs/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Content/Tabs/index.js
  packages/app/src/app/pages/Sandbox/Editor/Content/Tabs/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2878 Refactored liveinfo packages /app/src/app/pages/Sandbox/Editor/Workspace/items/Live/LiveInfo.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/LiveInfo.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/LiveInfo.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#3089 Improve error handling
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/overmind/effects/api/apiFactory.ts
  packages/app/src/app/overmind/effects/live/index.ts
  packages/app/src/app/overmind/factories.ts
  packages/app/src/app/overmind/internalActions.ts
  packages/app/src/app/overmind/namespaces/deployment/actions.ts
  packages/app/src/app/overmind/namespaces/deployment/internalActions.ts
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/overmind/namespaces/editor/internalActions.ts
  packages/app/src/app/overmind/namespaces/explore/actions.ts
  packages/app/src/app/overmind/namespaces/files/actions.ts
  packages/app/src/app/overmind/namespaces/workspace/actions.ts
  packages/app/src/app/overmind/onInitialize.ts
Labels: blocked, enhancement

#3190 Use console-feed upstream again
  packages/app/package.json
  yarn.lock
Labels: 📦 Dependencies

#3214 🔨 Switch LiveSessionEnded to use useOvermind
  packages/app/src/app/pages/common/Modals/LiveSessionEnded/elements.js
  packages/app/src/app/pages/common/Modals/LiveSessionEnded/elements.ts
  packages/app/src/app/pages/common/Modals/LiveSessionEnded/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2951 Open folder on drag over it / Ignore thumbnail cache files
  README.md
  packages/app/src/app/overmind/namespaces/files/actions.ts
  packages/app/src/app/overmind/namespaces/files/internalActions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/elements.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/index.tsx
  packages/common/src/sandbox/modules.ts
Labels: blocked, ✨ Feature

#3227 Add react-color types
  packages/app/package.json
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/TemplateConfig/index.tsx
  standalone-packages/vscode-textmate/package-lock.json
  yarn.lock
Labels: 📝 Types

#3218 🔨 Switch Header to use useOvermind
  packages/app/src/app/hooks/index.ts
  packages/app/src/app/hooks/useInterval.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/Action/Action.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/Action/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/Action/types.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ForkButton/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ForkButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ForkButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/LikeButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/LikeButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/PatronButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/PickButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/PickButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/UpdateFound/UpdateFound.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/UpdateFound/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/UpdateFound/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/UpdateFound/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/SaveAllButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ShareButton/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ShareButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/ShareButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Logo/Logo.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Logo/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/Logo/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/MenuBar/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/MenuBar/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/MenuBar/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/PrivacyTooltip/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/PrivacyTooltip/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/ViewMode/ViewMode.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/ViewMode/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/ViewMode/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/types.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3216 🔨 Switch FilterOptions to use useOvermind
  packages/app/src/app/overmind/namespaces/dashboard/actions.ts
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/Actions/index.tsx
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/FilterOptions/elements.ts
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/FilterOptions/index.tsx
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/index.tsx
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/index.tsx
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/types.ts
Labels: 🔨 Refactor, 🧠 Overmind
