Repository codesandbox/codesandbox-client, pull requests merged in 2019-10, with the labels that each got.

#2639 🔨 Refactored 🧠 Overmind Hacktober /pages/Sandbox/Editor/Header/CollectionInfo/index.js converted TS and uses Overmind
  packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/elements.js
  packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/index.js
  packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2722 Update users.json
  packages/homepage/content/users.json
Labels: 🚀Ready for deployment

#2724 Live: Don't send userEnter notification if notifications are turned off
  packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
Labels: 🔧 Fix

#2750 Add dev auth for localhost
  packages/app/src/app/overmind/internalActions.ts
  packages/app/src/app/pages/DevAuth/elements.ts
  packages/app/src/app/pages/DevAuth/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: AWESOME!

#2763 /app/pages/common/Modals/PreferencesModal/PaymentInfo/index 🔨 Refactor 🧠 Overmind Hacktoberfest
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/PaymentInfo.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/index.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2774 Refactored app/pages/common/Modals/ForkServerModal
  packages/app/src/app/pages/common/Modals/ForkServerModal/index.js
  packages/app/src/app/pages/common/Modals/ForkServerModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2776 🔨 Refactor, 🧠 Overmind | common/Modals/FeedbackModal/index.js
  packages/app/src/app/pages/common/Modals/FeedbackModal/index.js
  packages/app/src/app/pages/common/Modals/FeedbackModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2782 🔨 Refactor, 🧠 Overmind, Hacktoberfest - \app\src\app\pages\Sandbox\Editor\Workspace\Project\Project.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2780 refactor: /app/pages/Search/index.js 🔨 Refactor, 🧠 Overmind
  packages/app/src/app/pages/Search/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2759 Refactor | Overmind: Refactor /app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2807 refactor /app/pages/common/Modals/LiveSessionEnded/index.js to use Ov…
  packages/app/src/app/pages/common/Modals/LiveSessionEnded/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2768 🔨 Refactor, 🧠 Overmind | pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.js
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2663 🔨 Refactored 🧠 Overmind Hacktober | /Sandbox/Editor/Workspace/items/Live/index.js : refactor to replace Cerebral with Overmind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/index.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2806 🔨 Refactor, 🧠 Overmind | /app/pages/common/Modals/PreferencesModal/Appearance/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx
  packages/common/src/components/Preference/PreferenceText.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2635 🔨 Switch LikeHeart to use useOvermind
  packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/LikeButton/LikeButton.tsx
  packages/app/src/app/pages/common/LikeHeart/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2738 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/SiteInfo.tsx : replace Cerebral with Overmind & fixes NetlifySite id type
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/SiteInfo.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2655 Refactored 🧠 Overmind Hacktober | /app/pages/Sandbox/SignOutNoticeModal/index.js : refactor to replace Cerebral with Overmind
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/elements.ts
  packages/app/src/app/pages/Sandbox/SignOutNoticeModal/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2658 🔨 Refactor 🧠 Overmind /app/pages/NewSandbox/index.js
  packages/app/src/app/pages/NewSandbox/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2752 🔨 Refactored 🧠 Overmind Hacktober | app/.../PickSandboxModal
  packages/app/src/app/pages/common/Modals/PickSandboxModal/elements.tsx
  packages/app/src/app/pages/common/Modals/PickSandboxModal/index.js
  packages/app/src/app/pages/common/Modals/PickSandboxModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2720 🔨 Refactored 🧠 Overmind Hacktober | packages/app/src/app/pages/Dashboard/Content/CreateNewSandbo…
  README.md
  packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/index.js
  packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2729 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/Profile/index.js
  packages/app/package.json
  packages/app/src/app/components/ConfirmLink.tsx
  packages/app/src/app/pages/Dashboard/Content/routes/Templates/Templates.tsx
  packages/app/src/app/pages/Patron/index.tsx
  packages/app/src/app/pages/Profile/index.js
  packages/app/src/app/pages/Profile/index.tsx
  packages/app/src/app/pages/common/ErrorBoundary/ErrorBoundary.tsx
  packages/app/src/app/pages/common/ErrorBoundary/types.ts
  yarn.lock
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2742 🔨 Refactored 🧠 Overmind Hacktober | Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/AliasDeploymentButton/AliasDeploymentButton.tsx : refactor to replace Cerebral with Overmind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/AliasDeploymentButton/AliasDeploymentButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/types.ts
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2743 🔨 Refactored, 🧠 Overmind, Hacktober | Refactor SelectSandboxModal which now uses useOvermind
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/index.js
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2751 🔨 Refactored, 🧠 Overmind, Hacktober | Refactor MoveSandboxFolderModal to use overmind
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2737 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx : refactor to remove Cerebral
  packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2563 🔨 Switch TemplateConfig to use useOvermind
  packages/app/src/app/overmind/namespaces/workspace/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/Icon/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/TemplateConfig.tsx
  packages/common/src/types/index.ts
Labels: 🔨 Refactor, 🧠 Overmind

#2562 🔨 Switch SandboxConfig to use useOvermind
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/overmind/effects/api/index.ts
  packages/app/src/app/overmind/namespaces/workspace/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/SandboxConfig.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2758 🔨 Refactored, 🧠 Overmind, Hacktober | Refactor PreviewSettings to use overmind
  README.md
  packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/PreviewSettings/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2755 🔨Refactored 🧠 Overmind Hacktober | /app/pages/common/Modals/PRModal/index.js : refactor to replace Cerebral with Overmind
  packages/app/src/app/pages/common/Modals/PRModal/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2791 Embed redesign - release 1
  packages/app/package.json
  packages/app/src/app/pages/Sandbox/Editor/Content/Tabs/Tab/elements.ts
  packages/app/src/app/pages/common/Modals/ShareModal/index.js
  packages/app/src/embed/components/App/elements.js
  packages/app/src/embed/components/App/index.js
  packages/app/src/embed/components/Content/elements.ts
  packages/app/src/embed/components/EditorLink/elements.js
  packages/app/src/embed/components/EditorLink/index.js
  packages/app/src/embed/components/Header/elements.js
  packages/app/src/embed/components/Header/icons.js
  packages/app/src/embed/components/Header/index.js
  packages/app/src/embed/components/Sidebar/AvatarBlock/elements.js
  packages/app/src/embed/components/Sidebar/AvatarBlock/index.js
  packages/app/src/embed/components/Sidebar/Dependencies/elements.js
  packages/app/src/embed/components/Sidebar/Dependencies/index.js
  packages/app/src/embed/components/Sidebar/ExternalResources/elements.js
  packages/app/src/embed/components/Sidebar/ExternalResources/index.js
  packages/app/src/embed/components/Sidebar/FileTree/elements.js
  packages/app/src/embed/components/Sidebar/FileTree/icons.js
  packages/app/src/embed/components/Sidebar/FileTree/index.js
  packages/app/src/embed/components/Sidebar/FileTree/utils.js
  packages/app/src/embed/components/Sidebar/SandboxInfo/elements.js
  packages/app/src/embed/components/Sidebar/SandboxInfo/index.js
  packages/app/src/embed/components/Sidebar/Section/elements.js
  packages/app/src/embed/components/Sidebar/Section/index.js
  packages/app/src/embed/components/Sidebar/elements.js
  packages/app/src/embed/components/Sidebar/index.js
  packages/app/src/embed/components/legacy/File/elements.js
  packages/app/src/embed/components/legacy/File/index.js
  packages/app/src/embed/components/legacy/Files/elements.js
  packages/app/src/embed/components/legacy/Files/index.js
  packages/app/src/embed/index.html
  packages/app/src/embed/index.js
  packages/app/src/embed/theme/index.js
  packages/app/src/embed/theme/tokens.js
  packages/common/src/themes/codesandbox-nu.json
  packages/common/src/themes/index.ts
  yarn.lock
Labels: embed, enhancement

#2760 /app/pages/common/Modals/PreferencesModal/Badges/index.js 🔨 Refactor 🧠 Overmind Hacktoberfest
  packages/app/src/app/pages/common/Modals/PreferencesModal/Badges/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2727 Refactored | Overmind Hacktober | /app/pages/common/Modals/NetlifyLogs/index.js
  .all-contributorsrc
  README.md
  packages/app/src/app/pages/common/Modals/NetlifyLogs/elements.ts
  packages/app/src/app/pages/common/Modals/NetlifyLogs/index.js
  packages/app/src/app/pages/common/Modals/NetlifyLogs/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2886 add codesandboxer-fs docs
  packages/homepage/content/docs/2-importing.md
Labels: 📚 Documentation

#2883 fix #2792: added safe-check for undefined data.me
  packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/index.js
Labels: 📝 Types, 🔧 Fix

#2882 fix #2777: added safecheck for undefined data.me
  packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js
Labels: 📝 Types, 🔧 Fix

#2816 🔨 Refactor, 🧠 Overmind, Hacktoberfest - /app/pages/common/Modals/SelectSandboxModal/index.js
  packages/app/src/app/pages/common/Modals/SelectSandboxModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2863 🔨 Refactor, 🧠 Overmind, Hactoberfest | packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems
  packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/AnimatedSandboxItem.js
  packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/AnimatedSandboxItem.tsx
  packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/elements.ts
  packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/index.js
  packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/index.tsx
  packages/app/src/app/pages/Dashboard/Content/DragLayer/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2656 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/CliInstructions/index.tsx : refactor to replace Cerebral with Overmind
  packages/app/src/app/pages/CliInstructions/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2657 🔨Refactor /app/pages/GitHub/index.js
  packages/app/src/app/pages/GitHub/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2654 Refactored 🧠 Overmind Hacktober | patron/subscription: /app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.ts
  packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2803 🔨 Refactor, 🧠 Overmind, Hacktoberfest - /app/pages/common/Modals/PRModal/index.js: convert to tsx and uses overmind
  packages/app/src/app/components/GitProgress/GitProgress.tsx
  packages/app/src/app/pages/common/Modals/LiveSessionEnded/index.tsx
  packages/app/src/app/pages/common/Modals/PRModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.js
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind
