Repository codesandbox/codesandbox-client, pull requests merged in 2019-09, with the labels that each got.

#2376 ✨ Add URL to Crash Report, Add CodeSadbox route in Development
  packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/CodeSadbox.tsx
  packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/buildCrashReport.ts
  packages/app/src/app/pages/index.tsx
Labels: ✨ Feature

#2370 embed: make folders collapsable
  packages/app/src/embed/components/File/index.js
  packages/app/src/embed/components/Files/index.js
Labels: enhancement

#2377 Fix: React embed breaks with expanddevtools (only in dev mode)
  packages/common/src/templates/template.ts
Labels: embed, 🔧 Fix

#2378 [Fix] Embed: expandDevTools flag should override template default
  packages/app/src/embed/components/Content/index.tsx
Labels: embed, 🔧 Fix

#2392 Browser compatible jsonlint
  packages/app/config/webpack.common.js
  packages/common/package.json
  packages/common/src/templates/configuration/jsonlint.browser.js
  packages/common/src/templates/configuration/parse.ts
  yarn.lock
Labels: 🧰 Tooling

#2396 Fix jsonlint arguments bug
  packages/common/src/templates/configuration/jsonlint.browser.js
Labels: 🔧 Fix, 🧰 Tooling

#2394 Move jsonlint.browser to vendors + eslintignore it
  packages/common/.eslintignore
  packages/common/src/forked-vendors/README.md
  packages/common/src/forked-vendors/jsonlint.browser.js
  packages/common/src/templates/configuration/parse.ts
Labels: 🧰 Tooling

#2382 Use app logic for loading default file in embed
  packages/app/src/embed/components/App/index.js
  packages/app/src/embed/components/Content/index.tsx
  packages/common/src/sandbox/modules.ts
  packages/common/src/templates/configuration/resolve-module-wrapped.ts
Labels: embed, enhancement

#2409 Devtools: Add max limit for height
  packages/app/src/app/components/Preview/DevTools/index.tsx
Labels: 🔧 Fix

#2466 Download missing plugins from error
  packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
Labels: 🔧 Fix

#2519 🔨 Switch CreateRepo to useOvermind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/CreateRepo/CreateRepo.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2520 🔨 Switch Git to useOvermind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2498 🔨 Switch CodeSadbox to useOvermind, Remove title, add label to Report
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/CodeSadbox.tsx
  packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/buildCrashReport.ts
Labels: 🔨 Refactor, 🧠 Overmind
