Repository codesandbox/codesandbox-client, pull requests merged in 2019-11, with the labels that each got.

#2766 Refactor /app/pages/Profile/Showcase/index.js to /app/pages/Profile/Showcase/index.tsx 🔨 Refactor 🧠 Overmind Hacktoberfest
  packages/app/src/app/components/CodeEditor/Monaco/index.js
  packages/app/src/app/pages/Profile/Showcase/index.js
  packages/app/src/app/pages/Profile/Showcase/index.tsx
  packages/app/src/app/pages/Profile/index.tsx
  packages/common/src/components/flex/Column.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2918 :hammer: Refactor, 🧠 Overmind and hacktoberfest | changes done for app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
  .all-contributorsrc
  README.md
  packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2998 Embed: Change default of hideNavigation to true (with backward compatibility)
  packages/app/src/app/pages/common/Modals/ShareModal/index.js
Labels: embed, enhancement

#3015 Embeds: Add light theme
  packages/app/src/app/pages/common/Modals/ShareModal/getCode.js
  packages/app/src/app/pages/common/Modals/ShareModal/index.js
  packages/app/src/embed/components/App/elements.js
  packages/app/src/embed/components/App/index.js
  packages/app/src/embed/components/Content/elements.ts
  packages/app/src/embed/components/Content/index.tsx
  packages/app/src/embed/components/Sidebar/FileTree/elements.js
  packages/app/src/embed/components/Sidebar/SandboxInfo/elements.ts
  packages/app/src/embed/components/Sidebar/elements.js
  packages/app/src/embed/components/legacy/Header/elements.js
  packages/app/src/embed/components/legacy/Header/icons.js
  packages/app/src/embed/index.js
  packages/app/src/embed/theme/index.js
  packages/common/src/components/Preview/index.tsx
  packages/common/src/themes/codesandbox-light.json
  packages/common/src/themes/index.ts
  packages/common/src/url.ts
Labels: embed

#3016 Hide light theme behind feature flag
  README.md
  packages/app/scripts/sentry-create-release.js
  packages/app/src/app/pages/common/Modals/ShareModal/index.js
  packages/common/src/utils/feature-flags.js
  standalone-packages/codesandbox-browserfs/src/backend/CodeSandboxEditorFS.ts
Labels: embed, enhancement

#3018 Embeds: add secret url flag to hide dev tools
  packages/app/src/embed/components/Actions/elements.js
  packages/app/src/embed/components/Actions/index.js
  packages/app/src/embed/components/App/index.js
  packages/app/src/embed/components/Content/index.tsx
  packages/app/src/embed/components/SplitPane/index.js
  packages/common/src/__snapshots__/url.test.js.snap
  packages/common/src/url.ts
Labels: embed

#2957 fix(embed): likes counter on dislike shows inconsistent value
  packages/app/src/embed/components/App/index.js
Labels: embed

#2847 🔨 Switch Navigation to use useOvermind
  packages/app/src/app/components/Overlay/Overlay.tsx
  packages/app/src/app/overmind/namespaces/userNotifications/actions.ts
  packages/app/src/app/pages/common/Navigation/Actions/ExploreAction.tsx
  packages/app/src/app/pages/common/Navigation/Actions/NewSandboxAction.tsx
  packages/app/src/app/pages/common/Navigation/Actions/PatronAction.tsx
  packages/app/src/app/pages/common/Navigation/Actions/SearchAction.tsx
  packages/app/src/app/pages/common/Navigation/Actions/ShowNotificationsAction.tsx
  packages/app/src/app/pages/common/Navigation/Actions/index.ts
  packages/app/src/app/pages/common/Navigation/elements.ts
  packages/app/src/app/pages/common/Navigation/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#2893 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Dashboard/Content/routes/RecentSandboxes/index.js to use Overmind, Typescript, and Apollo hooks
  packages/app/src/app/pages/Dashboard/Content/Sandboxes/index.tsx
  packages/app/src/app/pages/Dashboard/Content/index.js
  packages/app/src/app/pages/Dashboard/Content/routes/RecentSandboxes/index.js
  packages/app/src/app/pages/Dashboard/Content/routes/RecentSandboxes/index.tsx
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#2902 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/common/Modals/index.js
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/pages/common/Modals/index.tsx
  packages/app/src/app/pages/index.tsx
  packages/app/src/app/utils/template-color.ts
Labels: Hacktoberfest, 🔨 Refactor, 🧠 Overmind

#3048 🔨 Switch Search to use useOvermind
  packages/app/src/app/pages/Search/elements.js
  packages/app/src/app/pages/Search/elements.ts
  packages/app/src/app/pages/Search/index.tsx
  packages/app/src/app/pages/Search/search.js
  packages/app/src/app/pages/Search/search.ts
  packages/app/src/app/pages/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3073 🔨 Switch CodeFormatting to use useOvermind
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3072 🔨 Switch Badges to use useOvermind
  packages/app/src/app/overmind/namespaces/preferences/actions.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Badges/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3069 🔨 Switch VisitSiteButton to use useOvermind
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/ClaimSiteButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/ClaimSiteButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/VisitSiteButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/VisitSiteButton/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/index.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3067 🔨 Switch CreateNewSandbox to use useOvermind
  packages/app/src/app/overmind/namespaces/dashboard/actions.ts
  packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/elements.ts
  packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/index.tsx
  packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js
  packages/app/src/app/pages/Dashboard/Content/routes/RecentSandboxes/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3095 Embed: Don't force run on click on mobile
  packages/app/src/embed/components/App/index.js
Labels: embed, enhancement

#3047 Delete CollectionInfo, since it's not used anymore
  packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/elements.js
  packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/index.tsx
Labels: 🔨 Refactor
