Repository codesandbox/codesandbox-client, pull requests merged in 2020-04, with the labels that each got.

#3818 textarea: minheight + autosize
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
  packages/components/src/components/Textarea/index.stories.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: UI/UX

#3822 Dialog performance - delay skeleton animation
  packages/app/src/app/constants.ts
  packages/app/src/app/overmind/effects/browser.ts
  packages/app/src/app/overmind/namespaces/comments/actions.ts
  packages/app/src/app/overmind/namespaces/comments/constants.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
Labels: UI/UX

#3843 Changelog
  packages/homepage/content/changelog/1-5-0/index.md
  packages/homepage/content/changelog/2-0-0/images/2-0.jpg
  packages/homepage/content/changelog/2-0-0/index.md
  packages/homepage/content/changelog/2-5-0/images/2-5.jpg
  packages/homepage/content/changelog/2-5-0/index.md
  packages/homepage/content/changelog/3-0-0/images/3-0.jpg
  packages/homepage/content/changelog/3-0-0/index.md
  packages/homepage/content/changelog/3-3-0/index.md
  packages/homepage/content/changelog/3-4-0/images/3-4.jpg
  packages/homepage/content/changelog/3-4-0/index.md
  packages/homepage/content/changelog/3-4-9-small-fixes/index.md
  packages/homepage/content/changelog/3-5-0-new-look-editor/images/3-5.jpg
  packages/homepage/content/changelog/3-5-0-new-look-editor/index.md
  packages/homepage/content/changelog/3-6-0-redefining-code-collaboration/images/3-6.jpg
  packages/homepage/content/changelog/3-6-0-redefining-code-collaboration/index.md
  packages/homepage/content/changelog/3-6-1/index.md
  packages/homepage/src/components/Footer/index.js
  packages/homepage/src/components/Navigation/index.js
  packages/homepage/src/pages/changelog/_elements.js
  packages/homepage/src/pages/changelog/index.js
Labels: UI/UX, 💬 Discussion, 📚 Documentation

#3869 Comments: Now the reply skeleton is actually themed
  packages/components/src/components/SkeletonText/index.tsx
Labels: 🔧 Fix

#3862 Correct link in test documents
  packages/homepage/content/docs/2-tests.md
Labels: 📚 Documentation

#3834 Updated docs screenshots, text, and styling
  packages/homepage/content/docs/2-live.md
  packages/homepage/content/docs/2-tests.md
  packages/homepage/content/docs/3-uploading.md
  packages/homepage/content/docs/5-secrets.md
  packages/homepage/content/docs/images/configuration.png
  packages/homepage/content/docs/images/create-wizard.png
  packages/homepage/content/docs/images/deployment-sidebar.png
  packages/homepage/content/docs/images/github-sidebar.png
  packages/homepage/content/docs/images/jest-squiggles.png
  packages/homepage/content/docs/images/live-classroom.png
  packages/homepage/content/docs/images/live-live.png
  packages/homepage/content/docs/images/live-make-editor.png
  packages/homepage/content/docs/images/live-make-spectator.png
  packages/homepage/content/docs/images/live-screenshot.png
  packages/homepage/content/docs/images/sandbox-private.png
  packages/homepage/content/docs/images/secrets-1.png
  packages/homepage/content/docs/images/secrets-2.png
  packages/homepage/content/docs/images/secrets-3.png
  packages/homepage/content/docs/images/secrets-4.png
  packages/homepage/content/docs/images/share-button.png
  packages/homepage/content/docs/images/storage-management-user.png
  packages/homepage/content/docs/images/storage-management-users.png
  packages/homepage/content/docs/images/templates/1.png
  packages/homepage/content/docs/images/templates/4.png
  packages/homepage/content/docs/images/templates/6.png
  packages/homepage/content/docs/images/upload.png
  packages/homepage/src/pages/blog/_elements.js
  packages/homepage/src/templates/_docs.elements.js
Labels: 📚 Documentation

#3865 3796 fix dependencies modal theme
  packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/elements.js
  packages/app/src/app/pages/Sandbox/SearchDependencies/RawAutoComplete/elements.js
  packages/app/src/app/pages/Sandbox/SearchDependencies/dependencies.js
  packages/app/src/app/pages/Search/search.ts
Labels: UI/UX

#3663 docs(adding-template): fix /sandbox/eval/index.ts link
  contributor-docs/adding-template.md
Labels: 📚 Documentation

#3888 chore: Update all embed frames
  packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts
  packages/common/src/components/Preview/index.tsx
  packages/homepage/content/docs/2-embedding.md
  packages/homepage/content/docs/2-importing.md
  packages/homepage/content/docs/2-tests.md
  packages/homepage/content/docs/5-secrets.md
  packages/homepage/src/screens/home/explore/index.js
  standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx
Labels: 📚 Documentation

#3690 experiment: version in status bar
  packages/app/src/app/pages/Sandbox/Editor/Skeleton/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Skeleton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
  packages/app/src/app/pages/Sandbox/Editor/index.tsx
Labels: enhancement

#3943 Make TS errors english
  packages/app/src/app/overmind/effects/vscode/initializers.ts
Labels: typescript

#3954 Dashboard - add header
  packages/app/src/app/pages/NewDashboard/Header/index.tsx
  packages/app/src/app/pages/NewDashboard/index.tsx
  packages/components/src/components/Icon/icons.tsx
Labels: UI/UX

#3965 Fix sentences in Live Docs first paragraph
  .all-contributorsrc
  README.md
  packages/homepage/content/docs/2-live.md
Labels: 📚 Documentation

#3962 [FIX] switch zeit now to Vercel Now for codesandbox deployment
  packages/homepage/content/docs/3-deployment.md
Labels: 📚 Documentation

#3995 Add icons for dashboard
  packages/components/src/components/Icon/icons.tsx
Labels: UI/UX

#3997 Sidebar with Icons
  packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Labels: UI/UX

#4010 menu design + fix grid
  packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx
  packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx
  packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
  packages/components/src/components/Menu/index.tsx
  packages/components/src/utils/polyfill-theme.ts
Labels: UI/UX

#3924 Privacy policy followup
  packages/app/src/app/overmind/internalActions.ts
  packages/app/src/app/overmind/onInitialize.ts
  packages/homepage/src/components/Toast/index.js
Labels: 📚 Documentation
