Repository codesandbox/codesandbox-client, pull requests merged in 2020-03, with the labels that each got.

#3604 Sidebar bugs + ad
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/BookmarkTemplateButton/BookmarkTemplateButton.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CommitForm.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
  packages/components/src/components/Icon/icons.tsx
  packages/components/src/components/Menu/index.tsx
  packages/components/src/index.ts
Labels: UI/UX

#3607 Make black theme the default
  packages/app/src/app/overmind/effects/vscode/initializers.ts
  packages/app/src/app/overmind/effects/vscode/theme-cache.ts
Labels: UI/UX

#3605 Turn on sidebar experiment for everyone
  packages/common/src/utils/feature-flags.ts
  packages/components/src/components/Icon/icons.tsx
Labels: UI/UX

#3614 fix alignment on collapsible
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx
  packages/components/src/components/Collapsible/index.tsx
Labels: UI/UX

#3618 Fix dependency dropdown for firefox
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
Labels: 🔧 Fix

#3620 Bring back theme preference initialiser
  packages/app/src/app/overmind/effects/vscode/initializers.ts
Labels: 🔧 Fix

#3619 add types for mutations
  packages/app/src/app/overmind/effects/fakeGql/comments/mutations.ts
  packages/app/src/app/overmind/effects/fakeGql/comments/queries.ts
  packages/app/src/app/overmind/effects/fakeGql/comments/types.ts
Labels: 📝 Types

#3622 Add inline code
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Comment.tsx
Labels: UI/UX

#3652 Fix typecheck error
  packages/app/src/app/overmind/namespaces/editor/actions.ts
Labels: 🏗️ CI/CD, 📝 Types, 🔥 Critical, 🔧 Fix, 🚨 ASAP

#3658 UI improvements for comments
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Comment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx
  packages/components/src/components/Element/index.tsx
  packages/components/src/components/Link/index.tsx
Labels: UI/UX, enhancement

#3661 Fix dependency picker hidden behind text
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
Labels: UI/UX, 🔧 Fix

#3670 Add open transition to menu
  packages/components/src/components/IconButton/index.tsx
  packages/components/src/components/Menu/index.tsx
  packages/components/src/components/Menu/menu.stories.tsx
Labels: UI/UX

#3689 Fix: Icons cant be on scale
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx
  packages/components/src/components/Icon/index.stories.tsx
  packages/components/src/components/Icon/index.tsx
Labels: UI/UX

#3662 Add FAQ to docs
  packages/homepage/content/docs/1-x-faqs.md
  packages/homepage/content/docs/images/dashboard-private.png
  packages/homepage/content/docs/images/sandbox-private.png
  packages/homepage/src/components/StickyNavigation.js
Labels: 📚 Documentation

#3634 Adding undocumented view options
  packages/homepage/content/docs/3-configuration.md
Labels: 📚 Documentation

#3687 Semantic changes to prepare for embed seo
  packages/app/src/embed/components/Sidebar/Dependencies/elements.js
  packages/app/src/embed/components/Sidebar/Dependencies/index.js
  packages/app/src/embed/components/Sidebar/SandboxInfo/elements.ts
  packages/app/src/embed/components/Sidebar/SandboxInfo/index.tsx
  packages/app/src/embed/components/Sidebar/elements.js
  packages/app/src/embed/components/Sidebar/index.js
Labels: embed

#3720 Don't use list.hover for file tree
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
Labels: UI/UX, enhancement

#3728 Comments polish 1
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/Dialog/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/Dialog/use-scroll-top.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/index.tsx
Labels: UI/UX

#3719 Handle long names in the sidebar
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx
  packages/components/src/components/Avatar/index.tsx
  packages/components/src/components/Text/index.tsx
Labels: UI/UX, 🔧 Fix

#3718 Show github repo in sandbox info
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/Icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx
Labels: UI/UX, enhancement

#3734 Contolled autosizing textarea
  packages/components/src/components/Textarea/index.stories.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: 🔧 Fix

#3724 Enhancements to skeleton
  packages/app/src/app/pages/Sandbox/Editor/Skeleton/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Skeleton/index.tsx
Labels: UI/UX, enhancement

#3798 Comments polish day 1
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
  packages/components/src/components/Icon/icons.tsx
Labels: UI/UX

#3801 Comments polish - Day 1, v2
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
Labels: UI/UX
