Repository codesandbox/codesandbox-client, pull requests merged in 2020-07, with the labels that each got.

#4030 Cleanup ProjectInfo screen
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Config.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Privacy.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary/EditSummary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary/TemplateConfig/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary/TemplateConfig/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/index.tsx
Labels: 🔨 Refactor

#4027 Cleanup Live screen
  packages/app/src/app/overmind/effects/live/index.ts
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/overmind/namespaces/live/actions.ts
  packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/CollaboratorHeads/CollaboratorHeads.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/Timer.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive/NotOwner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive/Owner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/index.tsx
Labels: 🔨 Refactor

#3429 🔨 Switch PreferencesModal to use useOvermind
  packages/app/src/app/overmind/namespaces/preferences/actions.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Badges.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/PreviewSettings.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/KeyMapping.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/Card/Icons.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/Card/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/SideNavigation.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/SideNavigation/index.js
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/OpenVSCodeSettingsButton.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder/index.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.tsx
  packages/app/src/app/pages/common/VercelIntegration.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#4529 Update Card component's height on User Settings
  packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/index.tsx
Labels: UI

#4582 Dashboard - only show counter for multiple items
  packages/app/src/app/pages/NewDashboard/Components/Selection/DragPreview.tsx
Labels: UX
