Repository codesandbox/codesandbox-client, pull requests merged in 2020-02, with the labels that each got.

#3474 Sidebar - fix position of delete button
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Config.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/index.tsx
Labels: UI/UX

#3476 Sidebar - fix dependencies overlap
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
  packages/components/src/components/Select/index.tsx
  packages/components/src/components/Text/index.tsx
Labels: UI/UX

#3492 More Polish
  packages/app/src/app/overmind/namespaces/live/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ConfigurationFiles/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Netlify.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotOwner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/BookmarkTemplateButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/BookmarkTemplateButton/mutations.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/BookmarkTemplateButton/queries.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Keywords.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/TemplateConfig.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/Control.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/EnvVars.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/Icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/Ports.tsx
  packages/app/src/app/pages/Sandbox/Editor/index.tsx
  packages/components/src/components/Text/index.tsx
  packages/components/src/index.ts
Labels: UI/UX

#3494 Sandbox summary v3?
  packages/app/src/app/overmind/namespaces/workspace/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/mutations.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/queries.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Description.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/EditSummary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/EditableTags.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Keywords.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Title.tsx
  packages/components/src/components/Input/index.tsx
  packages/components/src/components/Stack/index.tsx
  packages/components/src/components/TagInput/index.stories.tsx
  packages/components/src/components/TagInput/index.tsx
  packages/components/src/components/Tags/Tag.tsx
  packages/components/src/components/Tags/index.stories.tsx
  packages/components/src/components/Tags/index.tsx
  packages/components/src/index.ts
Labels: UI/UX

#3478 Update FUNDING.yml
  .github/FUNDING.yml
Labels: github

#3506 Small fixes
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ConfigurationFiles/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Netlify.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotOwner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CommitForm.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/GithubLogin.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/NotOwner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/EditSummary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Privacy.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/Ports.tsx
Labels: UI/UX

#3446 🔨 Switch MoveSandboxFolderModal to use useOvermind
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker.js
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/TeamsPicker/elements.ts
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/TeamsPicker/index.tsx
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/elements.ts
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/index.tsx
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/elements.ts
  packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3486 🔨 Switch Dashboard to use useOvermind
  packages/app/src/app/pages/Dashboard/elements.ts
  packages/app/src/app/pages/Dashboard/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3431 🔨 Switch PRModal to use useOvermind
  packages/app/src/app/components/GitProgress/index.ts
  packages/app/src/app/components/GitProgress/index.tsx
  packages/app/src/app/pages/common/Modals/PRModal/elements.ts
  packages/app/src/app/pages/common/Modals/PRModal/index.tsx
  packages/app/src/app/pages/common/Modals/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3509 Polish v6
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
  packages/common/src/themes/codesandbox.json
  packages/components/src/components/Avatar/index.tsx
  packages/components/src/components/Button/index.tsx
  packages/components/src/components/Collapsible/index.tsx
Labels: UI/UX

#3428 🔨 Switch OpenedTabs to use useOvermind
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/overmind/namespaces/live/actions.ts
  packages/app/src/app/overmind/utils/saveAllModules.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/GetIconURL.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/getIconURL.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryIcons/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/elements.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3440 🔨 Switch PickSandboxModal to use useOvermind
  packages/app/src/app/overmind/namespaces/explore/actions.ts
  packages/app/src/app/pages/common/Modals/PickSandboxModal/elements.ts
  packages/app/src/app/pages/common/Modals/PickSandboxModal/elements.tsx
  packages/app/src/app/pages/common/Modals/PickSandboxModal/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3427 🔨 Switch Profile/Sandboxes to use useOvermind
  packages/app/src/app/components/SandboxList/index.ts
  packages/app/src/app/components/SandboxList/index.tsx
  packages/app/src/app/overmind/namespaces/profile/actions.ts
  packages/app/src/app/pages/Profile/Sandboxes/NoSandboxes/elements.ts
  packages/app/src/app/pages/Profile/Sandboxes/NoSandboxes/index.tsx
  packages/app/src/app/pages/Profile/Sandboxes/elements.ts
  packages/app/src/app/pages/Profile/Sandboxes/elements.tsx
  packages/app/src/app/pages/Profile/Sandboxes/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3361 🔨 Switch Dependencies to use useOvermind
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddResource/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddResource/index.js
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddResource/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/ExternalResource.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/index.tsx
  packages/common/src/types/index.ts
Labels: 🔨 Refactor, 🧠 Overmind

#3408 🔨 Switch Profile/Navigation to use useOvermind
  packages/app/src/app/pages/Profile/Navigation/elements.js
  packages/app/src/app/pages/Profile/Navigation/elements.ts
  packages/app/src/app/pages/Profile/Navigation/index.js
  packages/app/src/app/pages/Profile/Navigation/index.tsx
  packages/app/src/app/pages/Profile/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3409 🔨 Switch Profile/Showcase to use useOvermind
  packages/app/src/app/pages/Profile/Showcase/LoadingSandbox.tsx
  packages/app/src/app/pages/Profile/Showcase/NoSandboxAvailable.tsx
  packages/app/src/app/pages/Profile/Showcase/SandboxInfo/elements.ts
  packages/app/src/app/pages/Profile/Showcase/SandboxInfo/index.tsx
  packages/app/src/app/pages/Profile/Showcase/elements.js
  packages/app/src/app/pages/Profile/Showcase/elements.ts
  packages/app/src/app/pages/Profile/Showcase/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3438 🔨 Switch StorageManagementModal to use useOvermind
  packages/app/src/app/overmind/namespaces/files/actions.ts
  packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/elements.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/index.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/DeleteFileButton/elements.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/DeleteFileButton/index.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/AddFileToSandboxButton.tsx
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/Button/elements.ts
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/Button/index.tsx
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/DeleteFileButton.tsx
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/elements.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/elements.ts
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/index.js
  packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/index.tsx
  packages/app/src/app/pages/common/Modals/StorageManagementModal/elements.ts
  packages/app/src/app/pages/common/Modals/StorageManagementModal/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3283 Delete all experimentVSCode branches from the code
  packages/app/src/app/overmind/actions.ts
  packages/app/src/app/overmind/effects/index.ts
  packages/app/src/app/overmind/effects/keybindingManager.ts
  packages/app/src/app/overmind/effects/settingsStore.ts
  packages/app/src/app/overmind/factories.ts
  packages/app/src/app/overmind/internalActions.ts
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/overmind/namespaces/editor/internalActions.ts
  packages/app/src/app/overmind/namespaces/preferences/actions.ts
  packages/app/src/app/overmind/namespaces/preferences/state.ts
  packages/app/src/app/overmind/onInitialize.ts
  packages/app/src/embed/components/Content/index.tsx
  packages/common/src/components/FeaturedSandbox/index.tsx
  packages/common/src/components/Preview/types.ts
  packages/common/src/types/index.ts
Labels: 🔨 Refactor

#3529 Danny's final feedback
  packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/GithubLogin.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/EditSummary.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/VarForm.tsx
  packages/common/src/theme/__snapshots__/theme.test.ts.snap
  packages/common/src/themes/codesandbox.json
  packages/components/src/components/Button/index.tsx
Labels: UI/UX

#3407 🔨 Switch Profile/Header to use useOvermind
  packages/app/src/app/pages/Profile/Header/UserInfo/ProfileInfo/elements.js
  packages/app/src/app/pages/Profile/Header/UserInfo/ProfileInfo/elements.ts
  packages/app/src/app/pages/Profile/Header/UserInfo/ProfileInfo/index.tsx
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/Badges/elements.ts
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/Badges/index.js
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/Badges/index.tsx
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/elements.ts
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/index.js
  packages/app/src/app/pages/Profile/Header/UserInfo/Stats/index.tsx
  packages/app/src/app/pages/Profile/Header/UserInfo/index.js
  packages/app/src/app/pages/Profile/Header/UserInfo/index.tsx
  packages/app/src/app/pages/Profile/Header/elements.ts
  packages/app/src/app/pages/Profile/Header/index.js
  packages/app/src/app/pages/Profile/Header/index.tsx
  packages/app/src/app/pages/Profile/index.tsx
  packages/common/src/components/ContributorsBadge/index.tsx
  packages/common/src/components/UserWithAvatar/elements.ts
  packages/common/src/components/UserWithAvatar/index.tsx
  packages/dynamic-pages/screens/Profile/Badges/elements.js
  packages/dynamic-pages/screens/Profile/Badges/index.js
Labels: 🔨 Refactor, 🧠 Overmind

#3568 Remove EMBED_LIGHT_THEME feature flag out of code since it's always true
  packages/app/src/app/pages/common/Modals/ShareModal/index.tsx
  packages/common/src/utils/feature-flags.js
Labels: 🔨 Refactor

#3556 Center text inside Input, Select, Textarea
  packages/components/src/components/Input/index.tsx
Labels: UI/UX

#3548 Components: extend react types to reduce repetition
  packages/components/package.json
  packages/components/src/components/Button/index.tsx
  packages/components/src/components/Input/index.tsx
  packages/components/src/components/Label/index.tsx
  packages/components/src/components/Label/label.stories.tsx
  packages/components/src/components/Link/index.tsx
  packages/components/src/components/Select/index.tsx
  packages/components/src/components/Tags/Tag.tsx
  packages/components/src/components/Text/index.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: 📝 Types

#3571 Sidebar enhacements
  packages/app/src/app/overmind/namespaces/preferences/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Navigation/elements.ts
  packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx
  packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
  packages/components/src/utils/polyfill-theme.ts
Labels: UI/UX

#3585 Sidebar feedback 999
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/FileInput.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
  packages/common/src/themes/codesandbox-black.js
  packages/components/src/components/Collapsible/index.tsx
Labels: UI/UX

#3592 Menu app styles which work with global styles
  packages/components/src/components/Menu/index.tsx
  packages/components/src/index.ts
Labels: UI/UX

#3595 Icon component
  packages/components/src/components/Icon/icons.tsx
  packages/components/src/components/Icon/index.stories.tsx
  packages/components/src/components/Icon/index.tsx
  packages/components/src/examples/sandbox-github.stories.tsx
  packages/components/src/index.ts
Labels: UI/UX

#3596 Icon button
  packages/components/src/components/Button/index.tsx
  packages/components/src/components/IconButton/iconbutton.stories.tsx
  packages/components/src/components/IconButton/index.tsx
Labels: UI/UX
