Repository codesandbox/codesandbox-client, pull requests merged in 2020-05, with the labels that each got.

#4032 Simplify master build
  .circleci/config.yml
Labels: 🏗️ CI/CD

#4056 Make grid at least have 4 elements + shadow instead of scale
  packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx
  packages/app/src/app/pages/NewDashboard/Components/SandboxGrid/index.tsx
Labels: UI/UX

#4060 Find a temporary place for settings
  packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
  packages/components/src/components/Icon/icons.tsx
Labels: UI/UX

#4075 Chromatic 2: project token is now a flag instead of process env
  packages/components/package.json
Labels: 🧰 Tooling

#3956 chore: Only run Chromatic when files are changed
  packages/components/package.json
Labels: 🏗️ CI/CD

#3838 Cleanup SandboxList
  packages/app/src/app/components/DeleteSandboxButton/DeleteSandboxButton.tsx
  packages/app/src/app/components/DeleteSandboxButton/elements.tsx
  packages/app/src/app/components/DeleteSandboxButton/index.ts
  packages/app/src/app/components/SandboxList/DeleteSandboxButton/elements.tsx
  packages/app/src/app/components/SandboxList/DeleteSandboxButton/index.tsx
  packages/app/src/app/components/SandboxList/index.tsx
  packages/app/src/app/pages/Profile/Sandboxes/index.tsx
Labels: 🔨 Refactor

#4026 Cleanup Deployment screen
  packages/app/src/app/overmind/namespaces/deployment/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Netlify.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotLoggedIn.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotOwner.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Vercel.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Vercel/elements.ts
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Vercel/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/icons.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/index.tsx
Labels: 🔨 Refactor

#4204 chore: Update all embed frames
  packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts
  packages/common/src/components/Preview/index.tsx
  packages/homepage/content/docs/2-embedding.md
  packages/homepage/content/docs/2-importing.md
  packages/homepage/content/docs/2-tests.md
  packages/homepage/content/docs/5-secrets.md
  packages/homepage/src/screens/home/explore/index.js
  standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx
  standalone-packages/sandpack/src/manager/index.ts
Labels: 📚 Docs
