Repository codesandbox/codesandbox-client, pull requests merged in 2020-01, with the labels that each got.

#3256 Components package
  .circleci/config.yml
  package.json
  packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/elements.ts
  packages/app/src/app/pages/Profile/Showcase/SandboxInfo/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Chat/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddFont/FontPicker/elements.ts
  packages/app/src/app/pages/common/LikeHeart/index.tsx
  packages/app/src/app/pages/common/Modals/FeedbackModal/Feedback.tsx
  packages/app/src/embed/components/Sidebar/SandboxInfo/index.tsx
  packages/common/package.json
  packages/common/src/components/Preference/PreferenceNumber.tsx
  packages/common/src/components/Preference/PreferenceText/index.tsx
  packages/common/src/theme/__snapshots__/theme.test.ts.snap 
  packages/components/.eslintignore
  packages/components/.eslintrc
  packages/components/.gitignore
  packages/components/.storybook/addons.ts
  packages/components/.storybook/config.tsx
  packages/components/.storybook/webpack.config.js
  packages/components/now.json
  packages/components/package.json
  packages/components/src/components/Example/index.stories.tsx
  packages/components/src/components/Example/index.tsx
  packages/components/src/stories/decorators/ThemeDecorator.tsx
  packages/components/src/stories/decorators/index.ts
  packages/components/src/utils/index.ts
  packages/components/tsconfig.json
  standalone-packages/vscode-textmate/package-lock.json
  yarn.lock
Labels: 🔨 Refactor

#3269 First component for new package: Collapsible
  packages/common/src/components/Preference/PreferenceNumber.tsx
  packages/common/src/design-language/index.ts
  packages/common/src/design-language/theme.ts
  packages/common/src/themes/codesandbox-black.js
  packages/components/.storybook/config.tsx
  packages/components/.storybook/decorators/ThemeDecorator.tsx
  packages/components/.storybook/decorators/index.ts
  packages/components/.storybook/theme.ts
  packages/components/src/components/Collapsible/index.stories.tsx
  packages/components/src/components/Collapsible/index.tsx
  packages/components/src/utils/polyfill-theme.ts
  yarn.lock
Labels: UI/UX

#3277 Layout components
  packages/components/.storybook/decorators/LayoutDecorator.tsx
  packages/components/.storybook/decorators/index.ts
  packages/components/src/components/Grid/grid.stories.tsx
  packages/components/src/components/Grid/index.tsx
  packages/components/src/components/Stack/index.tsx
  packages/components/src/components/Stack/stack.stories.tsx
Labels: UI/UX

#3280 add input to components package
  packages/common/src/design-language/theme.ts
  packages/common/src/themes/codesandbox-black.js
  packages/components/package.json
  packages/components/src/components/Example/index.stories.tsx
  packages/components/src/components/Input/index.stories.tsx
  packages/components/src/components/Input/index.tsx
  yarn.lock
Labels: UI/UX

#3291 components: use Text in Collapsible
  packages/components/src/components/Collapsible/index.stories.tsx
  packages/components/src/components/Collapsible/index.tsx
Labels: UI/UX

#3292 Add Textarea To Components
  .circleci/config.yml
  packages/components/.storybook/config.tsx
  packages/components/package.json
  packages/components/src/components/Example/index.tsx
  packages/components/src/components/Input/index.stories.tsx
  packages/components/src/components/Input/index.tsx
  packages/components/src/components/Textarea/index.stories.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: UI/UX

#3294 components: Add theme provider
  packages/components/.storybook/config.tsx
  packages/components/.storybook/decorators/ThemeDecorator.tsx
  packages/components/.storybook/theme.ts
  packages/components/src/components/ThemeProvider/index.tsx
Labels: UI/UX

#3295 Avatar
  packages/components/.storybook/config.tsx
  packages/components/src/components/Avatar/index.stories.tsx
  packages/components/src/components/Avatar/index.tsx
  packages/components/src/components/Avatar/stubs.ts
  packages/components/src/utils/polyfill-theme.ts
Labels: UI/UX

#3284 🔨 Switch Preview to use useOvermind
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3298 Select component
  packages/components/src/components/Select/index.stories.tsx
  packages/components/src/components/Select/index.tsx
Labels: UI/UX

#3297 Add Search Input
  packages/common/src/design-language/theme.ts
  packages/components/.storybook/config.tsx
  packages/components/src/components/Input/index.stories.tsx
  packages/components/src/components/SearchInput/index.stories.tsx
  packages/components/src/components/SearchInput/index.tsx
  packages/components/src/components/Textarea/index.stories.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: UI/UX

#3306 components: autosize for textarea
  packages/components/src/components/Textarea/index.stories.tsx
  packages/components/src/components/Textarea/index.tsx
Labels: UI/UX

#3296 components: Switch
  README.md
  packages/components/src/components/Grid/index.tsx
  packages/components/src/components/Switch/index.tsx
  packages/components/src/components/Switch/switch.stories.tsx
  packages/components/src/utils/polyfill-theme.ts
Labels: UI/UX

#3313 integration component
  packages/components/package.json
  packages/components/src/components/Integration/index.stories.tsx
  packages/components/src/components/Integration/index.tsx
  yarn.lock
Labels: UI/UX

#3331 Fix the type upgrades
  package.json
  packages/app/package.json
  packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/Chat/index.tsx
  packages/app/src/app/pages/common/LikeHeart/index.tsx
  packages/app/src/app/pages/common/Navigation/Actions/ShowNotificationsAction.tsx
  packages/codesandbox-api/package.json
  packages/common/package.json
  packages/executors/package.json
  packages/node-services/package.json
  packages/react-embed/package.json
  standalone-packages/react-sandpack/package.json
  standalone-packages/sandpack/package.json
  standalone-packages/vscode-textmate/package-lock.json
  yarn.lock
Labels: 📝 Types

#3358 Adds Create and Edit Template to new sidebar
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Config.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Privacy.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/TemplateConfig.tsx
  packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/index.tsx
  packages/components/src/components/Select/index.tsx
Labels: UI/UX

#3367 🔨 Switch ForkServerModal to use useOvermind
  packages/app/src/app/pages/common/Modals/ForkServerModal/elements.ts
  packages/app/src/app/pages/common/Modals/ForkServerModal/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3366 🔨 Switch SearchDependenciesModal to use useOvermind
  packages/app/src/app/pages/common/Modals/SearchDependenciesModal.tsx
  packages/app/src/app/pages/common/Modals/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind

#3352 🔨 Switch Profile to use useOvermind
  packages/app/src/app/overmind/namespaces/profile/actions.ts
  packages/app/src/app/pages/Profile/elements.ts
  packages/app/src/app/pages/Profile/index.tsx
  packages/app/src/app/pages/index.tsx
Labels: 🔨 Refactor, 🧠 Overmind
