Repository codesandbox/codesandbox-client, pull requests merged in 2021-06, with the labels that each got.

#5857 Discover: Infinite trail + banner config
  packages/app/src/app/pages/Dashboard/Content/routes/Discover/Curate.tsx
  packages/app/src/app/pages/Dashboard/Content/routes/Discover/contants.ts
  packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
  packages/app/static/img/discover-banner-decoration.png
  packages/app/static/img/discover-banner-search.png
Labels: UX

#5858 Discover: user selection: none
  packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
Labels: UX, 🐛 Bug

#5860 feat(tracking): editor more menu event
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/Alert.tsx
  packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
  packages/app/src/app/pages/Pro/pages/WorkspacePlanSelection.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
  packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborator.tsx
  packages/app/src/app/pages/common/Modals/NetlifyLogs/index.tsx
Labels: Product growth

#5862 feat(tracking): like in the dashboard
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/index.tsx
Labels: Product growth

#5814 UI/fixes
  packages/app/src/app/components/Modal/index.js
  packages/app/src/app/components/Notifications/index.tsx
  packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
  packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Labels: UI, UX

#5875 Homepage: new templates
  packages/homepage/gatsby-node.js
  packages/homepage/package.json
  packages/homepage/src/assets/icons/Plus.js
  packages/homepage/src/assets/icons/home-angular.svg
  packages/homepage/src/assets/icons/home-html.svg
  packages/homepage/src/assets/icons/home-js.svg
  packages/homepage/src/assets/icons/home-more.svg
  packages/homepage/src/assets/icons/home-react.svg
  packages/homepage/src/assets/icons/home-vue.svg
  packages/homepage/src/pages/index.js
  packages/homepage/src/screens/home/devExperienceOne/icons.js
  packages/homepage/src/screens/home/devExperienceOne/index.js
  packages/homepage/src/screens/home/hero/elements.js
  packages/homepage/src/screens/home/hero/index.js
  packages/homepage/src/screens/home/video/index.js
Labels: Product growth

#5866 feat(pages): add frameworks SEO pages
  packages/homepage/content/articles/announcing-codesandbox-2-0/index.md
  packages/homepage/content/articles/announcing-codesandbox-2-5/index.md
  packages/homepage/content/articles/announcing-codesandbox-containers/index.md
  packages/homepage/content/articles/announcing-codesandbox-custom-templates/index.md
  packages/homepage/content/articles/announcing-codesandbox-v3/index.md
  packages/homepage/content/articles/codesandbox-1-5-changelog/index.md
  packages/homepage/content/articles/codesandbox-an-online-react-editor/index.md
  packages/homepage/content/articles/codesandbox-containers-out-of-beta-improvements/index.md
  packages/homepage/content/articles/creating-a-parallel-offline-extensible-browser-based-bundler-for-codesandbox/index.md
  packages/homepage/content/articles/how-we-make-npm-packages-work-in-the-browser/index.md
  packages/homepage/content/articles/introducing-the-vanilla-template-to-codesandbox/index.md
  packages/homepage/content/articles/the-future-of-codesandbox/index.md
  packages/homepage/content/articles/whats-unique-about-codesandbox/index.md
  packages/homepage/content/seo/angular/banner.png
  packages/homepage/content/seo/angular/index.md
  packages/homepage/content/seo/gatsby/banner.png
  packages/homepage/content/seo/gatsby/index.md
  packages/homepage/content/seo/node/banner.png
  packages/homepage/content/seo/node/index.md
  packages/homepage/content/seo/nuxt/banner.png
  packages/homepage/content/seo/nuxt/index.md
  packages/homepage/content/seo/preact/banner.png
  packages/homepage/content/seo/preact/index.md
  packages/homepage/content/seo/react/banner.png
  packages/homepage/content/seo/react/index.md
  packages/homepage/content/seo/svelte/banner.png
  packages/homepage/content/seo/svelte/index.md
  packages/homepage/content/seo/vue/banner.png
  packages/homepage/content/seo/vue/index.md
  packages/homepage/gatsby-node.js
  packages/homepage/src/templates/seo.js
Labels: Product growth

#5898 feat(app): add ab framework to app
  packages/app/package.json
  packages/app/src/app/pages/Sandbox/Editor/Header/SignInAd.tsx
  packages/app/src/app/pages/index.tsx
  packages/common/src/config/env.ts
  packages/homepage/gatsby-browser.js
  packages/homepage/package.json
  yarn.lock
Labels: Product growth

#5914 Feat/live tracking
  packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/CollaboratorHeads/CollaboratorHeads.tsx
Labels: Product growth

#5882 feat(dashboard): add invite members link
  packages/app/src/app/pages/Dashboard/Content/routes/Settings/Invite.tsx
  packages/app/src/app/pages/Dashboard/Header/index.tsx
Labels: Product growth

#5919 Feat/dashboard invite members
  packages/app/src/app/overmind/namespaces/dashboard/actions.ts
  packages/app/src/app/pages/Dashboard/Content/routes/Settings/Invite.tsx
  packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
  packages/app/src/app/pages/Dashboard/Header/index.tsx
Labels: Product growth

#5915 feat(ab experiment): change trigger to show sign-in ads in the editor
  packages/app/src/app/overmind/namespaces/editor/actions.ts
  packages/app/src/app/overmind/namespaces/editor/state.ts
  packages/app/src/app/pages/Sandbox/Editor/Header/SignInAd.tsx
Labels: Product growth

#5854 New 2021 black theme
  packages/app/src/app/overmind/effects/vscode/initializers.ts
  standalone-packages/vscode-extensions/out/bundles/README.md
  standalone-packages/vscode-extensions/out/bundles/main.min.json
  standalone-packages/vscode-extensions/out/extensions/codesandbox-black-0.0.1/package.json
  standalone-packages/vscode-extensions/out/extensions/codesandbox-black-0.0.1/themes/codesandbox-black-2021.json
  standalone-packages/vscode-extensions/out/extensions/index.json
Labels: UI

#5924 Fix tag fetching
  packages/common/src/utils/dependencies.ts
Labels: 🎒 Bundler

#5920 feat(ab framework): update api url
  packages/common/src/config/env.ts
Labels: Product growth
